// <auto-generated />
using FPGA_Finder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FPGA_Finder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FPGA_Finder.Models.FPGA_Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("family");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("interface");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("purpose");

                    b.Property<string>("formFactor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("formFactor");

                    b.Property<int>("memoryGB")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("memoryGB");

                    b.Property<string>("memoryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("memoryType");

                    b.Property<int>("throughputGbps")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("throughputGbps");

                    b.Property<string>("typicalUseCase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("typicalUseCase");

                    b.HasKey("Id");

                    b.ToTable("FPGA_Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
